apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: b2
  name: b2
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: b2
    spec:
      containers:
      - image: torticounette/b02:latest
        name: b2
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
