apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: b3
  name: b3
spec:
  authentication:
    type: tls
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8080
  selector:
    io.kompose.service: b3
status:
  loadBalancer: {}
